server:
  port: 8090
  address: 127.0.0.1
  servlet:
    context-path: /blog


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
#    username: root
#    password: rd.123456

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: rd.123456
  aop:
    proxy-target-class: true

  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml


  mvc:
    static-path-pattern: /**







